CREATE TABLE DRUGS_FULL (
    DRUG_ID NUMBER(6),
    DRUG_NAME VARCHAR2(100),
    SIDE_EFFECT1 VARCHAR2(100),
    SIDE_EFFECT2 VARCHAR2(100),
    SIDE_EFFECT3 VARCHAR2(100),
    SIDE_EFFECT4 VARCHAR2(100),
    SIDE_EFFECT5 VARCHAR2(100),
    INTERACTS_WITH1 VARCHAR2(100),
    INTERACTS_WITH2 VARCHAR2(100),
    INTERACTS_WITH3 VARCHAR2(100),
    DISEASE_NAME VARCHAR2(200),
    DISEASE_CATEGORY VARCHAR2(100),
    DRUG_CATEGORY VARCHAR2(100),
    PRODUCT_ID NUMBER(6),
    PRODUCT_NAME VARCHAR2(150),
    COMPANY_NAME VARCHAR2(150),
    CLINICAL_TRIAL_TITLE VARCHAR2(300),
    CLINICAL_TRIAL_START_DATE VARCHAR2(50),
    CLINICAL_TRIAL_COMPLETION_DATE VARCHAR2(50),
    CLINICAL_TRIAL_PARTICIPANTS VARCHAR2(50),
    CLINICAL_TRIAL_STATUS VARCHAR2(50),
    CLINICAL_TRIAL_CONDITION1 VARCHAR2(100),
    CLINICAL_TRIAL_CONDITION2 VARCHAR2(100),
    --COUNTRY_ID NUMBER(6),
    CLINICAL_TRIAL_ADDRESS1 VARCHAR2(200),
    CLINICAL_TRIAL_INSTITUTION VARCHAR2(150),
    CLINICAL_TRIAL_ADDRESS2 VARCHAR2(200),
    CLINICAL_TRIAL_MAIN_RESEARCHER VARCHAR2(100),
    CLINICAL_TRIAL_CONDITION3 VARCHAR2(100)
);


SELECT * FROM DRUGS_FULL;